org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
# android.enableJetifier=true
dev.steenbakker.mobile_scanner.useUnbundled=true
org.gradle.java.home=/Users/izisolution/Library/Java/JavaVirtualMachines/corretto-17.0.14/Contents/Home
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false